// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "device", Scope = "member", Target = "BuildWatcher.SingleShotTimerContainingSerialPort.#device")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "rgb", Scope = "member", Target = "BuildWatcher.CheapLaunchpadMSP430.#Indicate(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "rgb", Scope = "member", Target = "BuildWatcher.CheapLaunchpadMSP430.#IndicateProblem(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.TfsBuildAdapter.#GetBuildDefinitions(Microsoft.TeamFoundation.VersionControl.Client.TeamProject,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.TfsBuildAdapter.#GetLastTwoBuilds(Microsoft.TeamFoundation.VersionControl.Client.TeamProject,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.TfsBuildAdapter.#GetQueuedBuilds(Microsoft.TeamFoundation.VersionControl.Client.TeamProject,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.TfsBuildAdapter.#NumberOfSuccessfulBuilds(BuildWatcher.LastTwoBuildResults[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.TfsBuildAdapter.#SomeoneIsBuilding(BuildWatcher.LastTwoBuildResults[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.Tfs.TfsBuildAdapter.#GetBuildDefinitions(Microsoft.TeamFoundation.VersionControl.Client.TeamProject,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.Tfs.TfsBuildAdapter.#GetLastTwoBuilds(Microsoft.TeamFoundation.VersionControl.Client.TeamProject,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.Tfs.TfsBuildAdapter.#GetQueuedBuilds(Microsoft.TeamFoundation.VersionControl.Client.TeamProject,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.Tfs.TfsBuildAdapter.#SomeoneIsBuilding(BuildWatcher.Tfs.TfsLastTwoBuildResults[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.Tfs.TfsBuildAdapter.#NumberOfSuccessfulBuilds(BuildWatcher.Tfs.TfsLastTwoBuildResults[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.Tfs.TfsBuildAdapter.#NumberOfPartiallySuccessfulBuilds(BuildWatcher.Tfs.TfsLastTwoBuildResults[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.Http.HttpListenerWrapper.#ListenerCallback(System.IAsyncResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "BuildWatcher.TfsBuildAdapter.#NumberOfPartiallySuccessfulBuilds(BuildWatcher.LastTwoBuildResults[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.CheapLaunchpadMSP430.#Indicate(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.Freemometer.#Indicate(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.CheapLaunchpadMSP430.#IndicateProblem(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.Freemometer.#IndicateProblem(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.Freemometer.#TurnOffRinger(System.Object,System.Timers.ElapsedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.Devices.Freemometer.#IndicateProblem(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.Devices.Freemometer.#TurnOffRinger(System.Object,System.Timers.ElapsedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.IO.Ports.SerialPort.Write(System.String)", Scope = "member", Target = "BuildWatcher.Devices.Freemometer.#Indicate(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "type", Target = "BuildWatcher.TfsBuildAdapter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "type", Target = "BuildWatcher.TfsBuildConnection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "tfs", Scope = "member", Target = "BuildWatcher.TfsBuildConnection.#.ctor(System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "member", Target = "BuildWatcher.TfsBuildConnection.#TfsUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "member", Target = "BuildWatcher.TfsBuildConnection.#TfsTeamProjects")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "namespace", Target = "BuildWatcher.Tfs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "type", Target = "BuildWatcher.Tfs.TfsLastTwoBuildResults")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "member", Target = "BuildWatcher.Tfs.TfsBuildConnection.#TfsTeamProjects")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tfs", Scope = "namespace", Target = "BuildWatcher.Tfs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]

